# Generated by Django 5.1.1 on 2024-09-07 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Care',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Care date')),
                ('action', models.CharField(choices=[('W', 'Watering'), ('F', 'Fertilizing'), ('L', 'Leaf Cleaning')], default='W', max_length=1)),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.plant')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
